export const meditationSounds: MeditationSound[] = [
  {
    id: '1',
    title: 'Silent Clock',
    listening: '59899 Listening',
    duration: 15,
    image: require('../assets/meditation/clock.jpg'),
  },
  {
    id: '2',
    title: 'Painting Forest',
    listening: '87342 Listening',
    image: require('../assets/meditation/amazon.jpg'),
    duration: 104,
  },
  {
    id: '3',
    title: 'Lovely Desert',
    listening: '69128 Listening',
    image: require('../assets/meditation/desert.jpg'),
    duration: 35,
  },
  {
    id: '4',
    title: 'Grassland Wind',
    listening: '41903 Listening',
    image: require('../assets/meditation/grassland.jpg'),
    duration: 47,
  },
  {
    id: '5',
    title: "The Hill Sides",
    listening: '75189 Listening',
    image: require('../assets/meditation/hillside.jpg'),
    duration: 52,
  },
  {
    id: 'string',
    title: 'Snowy Mountain',
    listening: '62457 Listening',
    image: require('../assets/meditation/snowy_mountain.jpg'),
    duration: 63,
  },
  {
    id: '6',
    title: 'Calm Tundra',
    listening: '59899 Listening',
    image: require('../assets/meditation/tundra.jpg'),
    duration: 28,
  },
  {
    id: '7',
    title: 'Colorful Landscape',
    listening: '93805 Listening',
    image: require('../assets/meditation/art_landscape.jpg'),
    duration: 20,
  },
]
