export const meditationSounds: MeditationSound[] = [
  {
    id: 1,
    title: 'Silent Clock',
    listening: '59899 Listening',
    duration: 15,
    image: require('../assets/meditation/clock.jpg'),
    sound: require('../assets/sounds/clock.mp3'),
    author: 'Silent Guy',
  },
  {
    id: 2,
    title: 'Painting Forest',
    listening: '87342 Listening',
    image: require('../assets/meditation/amazon.jpg'),
    sound: require('../assets/sounds/amazon.mp3'),
    duration: 104,
    author: 'Lily Rose',
  },
  {
    id: 3,
    title: 'Lovely Desert',
    listening: '69128 Listening',
    image: require('../assets/meditation/desert.jpg'),
    sound: require('../assets/sounds/art_landscape.mp3'),
    duration: 35,
    author: 'John Paul',
  },
  {
    id: 4,
    title: 'Grassland Wind',
    listening: '41903 Listening',
    image: require('../assets/meditation/grassland.jpg'),
    sound: require('../assets/sounds/amazon.mp3'),
    duration: 47,
    author: 'Emma Jane'
  },
  {
    id: 5,
    title: "The Hill Sides",
    listening: '75189 Listening',
    image: require('../assets/meditation/hillside.jpg'),
    duration: 52,
    author: "Michaela Smith",
    sound: require('../assets/sounds/art_landscape.mp3'),
  },
  {
    id: 6,
    title: 'Snowy Mountain',
    listening: '62457 Listening',
    image: require('../assets/meditation/snowy_mountain.jpg'),
    sound: require('../assets/sounds/clock.mp3'),
    duration: 63,
    author: "Catherine Jones"
  },
  {
    id: 7,
    title: 'Calm Tundra',
    listening: '18347 Listening',
    image: require('../assets/meditation/tundra.jpg'),
    sound: require('../assets/sounds/amazon.mp3'),
    duration: 28,
  },
  {
    id: 8,
    title: 'Colorful Landscape',
    listening: '93805 Listening',
    image: require('../assets/meditation/art_landscape.jpg'),
    sound: require('../assets/sounds/art_landscape.mp3'),
    duration: 20,
    author: "Lian Scott"
  },
]
